version: '3.6'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8080"
      - "50000"
    container_name: jenkins
    
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=archerysec
      - POSTGRES_PASSWORD=archerysec
      - POSTGRES_USER=archerysec

  archerysec:
    image: archerysec/archerysec
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DB_PASSWORD=archerysec
      - DB_USER=archerysec
      - DB_NAME=archerysec
      - DB_HOST=db
      - NAME=admin
      - EMAIL=admin@test.com
      - PASSWORD=admin
      - DJANGO_SETTINGS_MODULE=archerysecurity.settings.development
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-"SETME"}
      - DJANGO_DEBUG=1
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    container_name: archerysec

    #  clair:
    #image: quay.io/coreos/clair:latest
    #volumes:
    #  - ./config.yaml:/etc/clair/config.yaml
    #environment:
    #  CLAIR_CONFIG: /etc/clair/config.yaml
    #ports:
    #  - "6060:6060"
    #  - "6061:6061"
    #depends_on:
    #  - db
    #links:
    #  - db:db
  zaproxy:
    image: owasp/zap2docker-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8090:8090"
    expose:
    # ZAP is running on 8090, we want it to be accessible by our tools
      - "8090"
    links:
      - archerysec
    container_name: zapscanner
#Anchore
  anchore-api:
    image: anchore/anchore-engine:v1.0.0
    depends_on:
      - db
      - catalog
    ports:
      - "8228:8228"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=api
      - ANCHORE_ADMIN_PASSWORD=admin
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_USER=archerysec
      - ANCHORE_DB_PASSWORD=archerysec
    command: ["anchore-manager", "service", "start", "apiext"]
  catalog:
    image: anchore/anchore-engine:v1.0.0
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    expose:
      - 8228
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=catalog
      - ANCHORE_ADMIN_PASSWORD=admin
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_USER=archerysec
      - ANCHORE_DB_PASSWORD=archerysec
    command: ["anchore-manager", "service", "start", "catalog"]
  queue:
    image: anchore/anchore-engine:v1.0.0
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=queue
      - ANCHORE_ADMIN_PASSWORD=admin
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_USER=archerysec
      - ANCHORE_DB_PASSWORD=archerysec
    command: ["anchore-manager", "service", "start", "simplequeue"]
  policy-engine:
    image: anchore/anchore-engine:v1.0.0
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=policy-engine
      - ANCHORE_ADMIN_PASSWORD=admin
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_USER=archerysec
      - ANCHORE_DB_PASSWORD=archerysec
      - ANCHORE_VULNERABILITIES_PROVIDER=grype
    command: ["anchore-manager", "service", "start", "policy_engine"]
  analyzer:
    image: anchore/anchore-engine:v1.0.0
    depends_on:
      - db
      - catalog
    expose:
      - 8228
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    environment:
      - ANCHORE_ENDPOINT_HOSTNAME=analyzer
      - ANCHORE_ADMIN_PASSWORD=admin
      - ANCHORE_DB_HOST=db
      - ANCHORE_DB_USER=archerysec
      - ANCHORE_DB_PASSWORD=archerysec
    volumes:
      - /analysis_scratch
    command: ["anchore-manager", "service", "start", "analyzer"]
